# Generated by Django 5.2.4 on 2026-01-21 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(max_length=100)),
                ('vehicle_name', models.CharField(max_length=100)),
                ('vehicle_type', models.CharField(choices=[('car', 'Car'), ('bike', 'Bike')], max_length=10)),
                ('category', models.CharField(max_length=50)),
                ('price_per_day', models.IntegerField()),
                ('seats', models.IntegerField(blank=True, null=True)),
                ('fuel_type', models.CharField(max_length=30)),
                ('pickup_location', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='vehicles/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
