# Generated by Django 5.2.4 on 2026-01-21 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='category',
            field=models.CharField(choices=[('All', 'All'), ('Touring', 'Touring'), ('Sedan', 'Sedan'), ('Hatchback', 'Hatchback'), ('SUV', 'SUV'), ('Dual-Sport', 'Dual-Sport'), ('Crossover (CUV)', 'Crossover (CUV)'), ('Off-Road 1 Dirt Bike', 'Off-Road 1 Dirt Bike'), ('Coupe', 'Coupe'), ('Scooter', 'Scooter'), ('MPV/Minivan', 'MPV/Minivan'), ('Moped', 'Moped'), ('Convertible', 'Convertible'), ('Pickup Truck', 'Pickup Truck'), ('Standard (Naked)', 'Standard (Naked)'), ('Sportbike', 'Sportbike'), ('Cruiser', 'Cruiser'), ('Adventure (ADV)', 'Adventure (ADV)'), ('Electric Motorcycle', 'Electric Motorcycle')], max_length=50),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='fuel_type',
            field=models.CharField(choices=[('Petrol', 'Petrol'), ('Diesel', 'Diesel'), ('Electric', 'Electric'), ('Hybrid', 'Hybrid')], max_length=30),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='seats',
            field=models.IntegerField(blank=True, choices=[(2, '2'), (4, '4'), (8, '8'), (12, '12+')], null=True),
        ),
    ]
