# Generated by Django 5.2.4 on 2026-01-21 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_vehicle_category_alter_vehicle_fuel_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='image',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='contact_number',
            field=models.CharField(default=0, max_length=15),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='VehicleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='vehicles/')),
                ('image_type', models.CharField(choices=[('front', 'Front'), ('back', 'Back'), ('inside', 'Inside')], max_length=10)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.vehicle')),
            ],
        ),
    ]
