# Generated by Django 5.2.4 on 2026-01-22 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rental'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='aadhaar_image',
            field=models.ImageField(default='documents/placeholder.png', upload_to='documents/aadhaar/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rental',
            name='age',
            field=models.IntegerField(default=18),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rental',
            name='full_name',
            field=models.CharField(default='Unknown Name', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rental',
            name='license_image',
            field=models.ImageField(default='documents/placeholder.png', upload_to='documents/license/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rental',
            name='phone_number',
            field=models.CharField(default=0, max_length=15),
            preserve_default=False,
        ),
    ]
