# Generated by Django 5.2.4 on 2026-01-22 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rental_aadhaar_image_rental_age_rental_full_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
