# Generated by Django 5.2.4 on 2026-01-30 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_vehicle_owner_name_vehicle_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='drive_type',
            field=models.CharField(choices=[('self', 'Self-Driving'), ('driver', 'With GoWheels Driver')], default='self', max_length=10),
        ),
    ]
