# Generated by Django 5.2.4 on 2026-01-30 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_rental_drive_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('experience_years', models.IntegerField()),
                ('rating', models.FloatField(default=0)),
                ('price_per_day', models.IntegerField()),
                ('photo', models.ImageField(upload_to='drivers/')),
                ('available', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='rental',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.driver'),
        ),
    ]
