# Generated by Django 5.2.4 on 2026-01-30 10:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_driver_rental_driver'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='rating',
            field=models.FloatField(default=5.0),
        ),
        migrations.CreateModel(
            name='DriverApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('phone_number', models.CharField(max_length=15)),
                ('experience_years', models.IntegerField()),
                ('rating', models.FloatField(default=5.0)),
                ('price_per_day', models.IntegerField()),
                ('aadhaar_image', models.ImageField(upload_to='driver_docs/aadhaar/')),
                ('license_image', models.ImageField(upload_to='driver_docs/license/')),
                ('profile_photo', models.ImageField(upload_to='driver_docs/profile/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
