# Generated by Django 5.2.4 on 2026-01-30 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_driver_rating_driverapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='aadhaar_image',
            field=models.ImageField(blank=True, null=True, upload_to='driver_docs/aadhaar/'),
        ),
        migrations.AddField(
            model_name='driver',
            name='license_image',
            field=models.ImageField(blank=True, null=True, upload_to='driver_docs/license/'),
        ),
        migrations.AddField(
            model_name='driver',
            name='phone_number',
            field=models.CharField(default=9998887770, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='driver',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='drivers/'),
        ),
    ]
