# Generated by Django 5.2.4 on 2026-01-30 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_driver_aadhaar_image_driver_license_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='application',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='driver', to='main.driverapplication'),
        ),
    ]
