# Generated by Django 5.2.4 on 2026-02-04 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_driver_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rental', to='main.vehicle'),
        ),
    ]
