# Generated by Django 5.2.4 on 2026-02-12 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_wallet_wallettransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='payment_mode',
            field=models.CharField(choices=[('cash', 'Cash on Pickup'), ('online', 'Online Payment')], default='cash', max_length=10),
        ),
    ]
