# Generated by Django 5.2.4 on 2026-03-06 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='application',
        ),
        migrations.DeleteModel(
            name='DriverApplication',
        ),
    ]
