# Generated by Django 5.2.4 on 2026-03-25 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_vehicle_vehicle_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='category',
            field=models.CharField(choices=[('All', 'All'), ('Touring', 'Touring'), ('Sedan', 'Sedan'), ('Hatchback', 'Hatchback'), ('SUV', 'SUV'), ('Dual-Sport', 'Dual-Sport'), ('Crossover (CUV)', 'Crossover (CUV)'), ('Off-Road 1 Dirt Bike', 'Off-Road 1 Dirt Bike'), ('Coupe', 'Coupe'), ('Scooter', 'Scooter'), ('MPV/Minivan', 'MPV/Minivan'), ('Moped', 'Moped'), ('Convertible', 'Convertible'), ('Pickup Truck', 'Pickup Truck'), ('Standard (Naked)', 'Standard (Naked)'), ('Sportbike', 'Sportbike'), ('Cruiser', 'Cruiser'), ('Adventure (ADV)', 'Adventure (ADV)'), ('Electric Motorcycle', 'Electric Motorcycle'), ('Minibus', 'Minibus')], max_length=50),
        ),
    ]
