# Generated by Django 5.2.4 on 2026-03-26 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_alter_vehicle_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='promo_code',
            field=models.CharField(blank=True, help_text='Coupon code used during checkout.', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='rental',
            name='special_notes',
            field=models.TextField(blank=True, help_text='Any special requests from the user.', null=True),
        ),
    ]
