# Generated by Django 5.2.4 on 2026-04-01 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_alter_rental_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
