# Generated by Django 5.2.4 on 2026-04-02 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_vehicle_vehicle_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='cash_on_pickup_blocked',
            field=models.BooleanField(default=False, help_text='Blocked from using Cash payment due to past cancellation/no-show.'),
        ),
    ]
