# Generated by Django 5.2.4 on 2026-04-02 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_userprofile_cash_on_pickup_blocked'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='actual_return_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rental',
            name='penalty_applied',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='rental',
            name='security_deposit_held',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='rental',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active/Ongoing'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=20),
        ),
        migrations.AlterField(
            model_name='rental',
            name='payment_mode',
            field=models.CharField(choices=[('cash', 'Cash on Pickup'), ('online', 'Online Payment'), ('upi', 'UPI Payment'), ('wallet', 'Wallet Payment')], default='cash', max_length=20),
        ),
        migrations.AlterField(
            model_name='rental',
            name='promo_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='rental',
            name='special_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
